# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn clean test
  
  test-tunnel:
    runs-on: ubuntu-latest
    steps:
    - name: Start Tunnel
      uses: LambdaTest/LambdaTest-tunnel-action@v1
      id: tunnel
      with:
         user: suparna3107@gmail.com
         accessKey: NxNK9ORUuJXOv1aCcjGncMC7nrDsfAyjDhHf6jb19UxsDHgGL0
         tunnelName: "testTunnel"
    - run: mvn clean test -f /sample-maven-app/pom.xml
    - name: Export Tunnel Logs for debugging
      uses: actions/upload-artifact@v2
      with:
         name: tunnel_logs
         path: ${{ steps.tunnel.outputs.logFileName }}

